### ISSUE TITLE
Add GitHub action to run E2E tests against nightly Argo CD, w/ ApplicationSet master branch

### ISSUE THREAD

**Issue by jgwest** [argoproj/applicationset#363]
Argo CD continues to evolve on its `master` branch, and it would be useful to have a nightly cron-style GitHub Action that runs the `master` branch of ApplicationSets, specifically the controller and E2E tests, against the `master` branch of Argo CD. 

This would allow us to catch any runtime-behaviour changes in Argo CD that might affect ApplicationSets users (and would allow us to report them to the upstream project ASAP).

**Comment by shuker85** [comment]
Hi @jgwest 
If you can provide some guidance i'd like to work on this.
