### ISSUE TITLE
Add Bitbucket cloud support to SCM generator

### ISSUE THREAD

**Issue by jdomag** [argoproj/applicationset#459]
Would be great to have BitBucket cloud as a provide in SCM generator:
https://argocd-applicationset.readthedocs.io/en/stable/Generators-SCM-Provider/#scm-provider-generator

**Comment by mmerrill3** [comment]
Would access be by using a personal access token?  That can be passed as a bearer token, from the docs here: https://confluence.atlassian.com/bitbucketserver072/personal-access-tokens-1005335924.html

**Comment by mmerrill3** [comment]
The cloud based version of bitbucket also doesn't have labels.  There is the idea of a workspace, so if you need to group respositories together, I guess they could be put in the same workspace.  That's not really the intent of a workspace though.  At least I don't see the ability to put labels on repositories in the cloud version of bitbucket.

**Comment by jdomag** [comment]
@mmerrill3 is the labels something required? I could imagine that scanning whole workspace is fine. 
Access would be via App Password https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/ with option to reuse credentials defined for argocd - I've already have a password to bitbucket there, would be nice to reuse it instead of adding new one.

**Comment by mmerrill3** [comment]
@jdomag , labels are not required.  They just would be empty in the scm_provider.Repository structure.

The other two scm providers, gitlab and github.com, use static access tokens for authenticating with the cloud provider.  I see that bitbucket does as well, if you pass in the static access token as a bearer token, and the go client library for bitbucket supports that method as well.

If we use an app password, we would also need to pass in a username as well, which is an extra configuration parameter.  On the other hand, using the static token approach would be just one configuration setting.

**Comment by jdomag** [comment]
@mmerrill3 I think Personal Access Tokens are not available on BitBucket cloud: 
https://community.atlassian.com/t5/Bitbucket-questions/Personal-Access-Token-for-Bitbucket-Cloud/qaq-p/677663

**Comment by Lp-Francois** [comment]
It would be awesome to have bitbucket added :)

**Comment by mlosicki** [comment]
I know it's in the title, but is this issue strictly limited to Bitbucket Cloud (i.e. API 2.0)?

For those interested in Bitbucket Server (i.e. API 1.0), I have an implementation for SCM and PR generators [on this branch](https://github.com/mlosicki/applicationset/tree/feature/bitbucket-server-scm-and-pr)

**Comment by mmerrill3** [comment]
Thanks @mlosicki , the bitbucket server supports labels now if you'd like to use it.  That's great work.  I do get the sense that this is for Bitbucket Cloud.

**Comment by mmerrill3** [comment]
This is related to #472, since there's a change in the interface in that PR if it gets merged.  I was holding off on looking deeper into this ask until that PR had movement.

**Comment by YannayH** [comment]
Hey @mlosicki,
Loved what you did with Bitbucket Server (as my organization uses it currently). Would love if you open a PR to the main repository, and that your feature will be in the next version so everyone could use it!

**Comment by mmerrill3** [comment]
@jdomag the PR is merged, this issue can be closed.

**Comment by jdomag** [comment]
@mmerrill3  that's great news! I will give it a try in the next release of applicationSet controller!
thanks!

**Comment by Lp-Francois** [comment]
Hello!
Does it mean bitbucket will be included as a Generator Pull Request https://argocd-applicationset.readthedocs.io/en/stable/Generators-Pull-Request/ ?

**Comment by s7an-it** [comment]
Does this mean path generator annotation should work @mmerrill3 because on my current test with Bitbucket on webhooks it is being ignored?
