### ISSUE TITLE
ApplicationSet CRD size reduction, by removing validation (CRD defn) of nested merge/matrix generator

### ISSUE THREAD

**Issue by jgwest** [argoproj/applicationset#462]
## Problem

The large increase in the size of the ApplicationSet CRD has caused a couple significant issues:
1) Controller/operator bundling tools, such as [OLM](https://github.com/operator-framework/operator-lifecycle-manager), are unable to package CRDs that are this large. Even though the CRD is less than the size supported by `kubectl apply` and/or the underlying etcd db, the overall size still exceeds this threshold when packaged together with other CRDs plus additional controller installation metadata, as is the case with OLM. 
2) **See EDIT below**. *Original text*: When `kubectl apply`ing changes to the new ApplicationSet CRD, @jannfis observed that `kubectl` was stuck for 10+ minutes in trying to apply that CRD (and using a lot of CPU while doing so). This implies that the operation of diffing the structures of the old and new CRD is complex enough to make supporting a CRD this large potentially unworkable.
    - **EDIT**: Got an update from @jannfis that he might have had an older kubectl binary that [had this issue](https://github.com/kubernetes/kubectl/issues/919), which is our guess on what caused the excess CPU usage and long wait time issues. (I had seen this same issue previously, with an earlier version of the CRD, so it is likely unrelated to the CRD size increase.) So likely point 2) is likely no longer valid.

## Proposed solution

Our proposed solution is to remove validation (e.g. OpenAPI type information) from the nested Matrix/Merge generator (`NestedMergeGenerator`/`NestedMatrixGenerator` in the code) objects in the CRD. We would convert them to `apiextensionsv1.JSON` in the corresponding Go structs, which `controller-gen` will convert into `type: object` in the OpenAPI schema.
- The nested fields *will* still be validated, but rather than failing on resource creation (e.g. `kubectl apply`), instead the ApplicationSet controller will report an error (in the console log, and in `status` condition)  when the format of these fields cannot be unmarshalled to the expected structure.
- This does not affect non-nested Merge/Matrix generator scenarios, which work as before.

Since nesting a merge/matrix generator within another merge/matrix generator is IMHO an advanced feature, my expectation is that users using the functionality are likely to have the wherewithal to fix validation problems in the fields if they arise, e.g. without requiring explicit CR validation on resource creation.

This reduces the size of the ApplicationSet CRD from 836KB to 341KB. This is smaller than the size of the CRD in v0.2.0 (but, this is not an apples-to-apples comparison, because the v0.2.0 CRD included the `description` fields, whereas v0.3.0 still does not).

**Comment by crenshaw-dev** [comment]
Should we look at restoring the `description` fields, since those shouldn't affect CPU load?

**Comment by jgwest** [comment]
@crenshaw-dev We're now much less convinced it's a CPU issue, now that we found a kubectl that seems related. I've edited the problem description text with the details. So it's mainly just an issue with the overall size (in KB of text), and the description fields would probably add to that.
