### ISSUE TITLE
Github rate limit

### ISSUE THREAD

**Issue by fardin01** [argoproj/applicationset#464]
The SCM Provider Generator is a great tool for discovering the repos that have something to deploy to Kubernetes. The only problem is, it makes a ton of API requests to Github and very quickly gets rate limited. My Github org has around 600 repos which I don't think is unusually high.

One place for optimization I believe is [this line](https://github.com/argoproj/applicationset/blob/master/pkg/services/scm_provider/github.go#L67). It seems that [list-branches](https://developer.github.com/v3/repos/#list-branches) API is called once for every repo in the org. If a `filter` is specified (which I believe is the case most of the time), then the filter should be taken into account here to avoid calling `list-branches` for repos that we are not interested in. I will look for more places that can be optimized.

Is there someone intersted in looking into this?

**Comment by mmerrill3** [comment]
Would a topics filter help out here?  Let's say a repo has a topic of "agocd-target", and there was an option to filter on this topic?  It would be github.com specific though.

**Comment by fardin01** [comment]
I think it would definitely help out. There is a `labelMatch` filter already, so we could just compare that with the topics of each repo (returned by `ListByOrg`) and if there is no match, we skip calling `list-branches` API.  Exact same thing can be done using `allBranches` attribute as well as `repositoryMatch` filter.

Like I said I have ~ 600 repos in my org, so it should take a maximum of [6 API calls](https://github.com/argoproj/applicationset/blob/377b7e5b816d4e7b792bf89484fa2d85c6f70609/pkg/services/scm_provider/github.go#L46-L51) to get most of the information we need.

**Comment by enys** [comment]
I'm confirming this. Hitting also the problem.
It also seems the requeueAfterSeconds is not behaving as expected.

**Comment by mmerrill3** [comment]
This logic also exists in the other scm_provider, gitlab.  The fix would be to add another function to the scm_provider interface to fill in the branches after the utils class filters the repos.  [Here](https://github.com/argoproj/applicationset/blob/c8fb714a35fc66805fdb184dd5e6455637d5a8b4/pkg/services/scm_provider/utils.go#L108), probably.  That's where the new function call would be to fill in the branches for all the scm_providers.

**Comment by fardin01** [comment]
Sounds good @mmerrill3. Looking forward to seeing what you'll put together 🚀

**Comment by fardin01** [comment]
@enys In the meantime, if you have Github Enterprise Cloud, you can create an OAuth token that has a 15k/hour rate limit, and in my case, it is JUST enough.

**Comment by enys** [comment]
Yup that's more or less what I did. :) Thanks
