### ISSUE TITLE
skipCrds is missing from the Helm Resource for the applicationset CRD

### ISSUE THREAD

**Issue by EStork09** [argoproj/applicationset#501]
skipCrds has been added to the application resource such as [this](https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml#L269).

Applicationset currently doesn't support this as a resource for the [crd resource](https://github.com/argoproj/applicationset/blob/8220c8a6e49e6f4c773a25d09b091aa7bab2ff3f/manifests/crds/argoproj.io_applicationsets.yaml#L189-L223) I am not sure if it is as easy as just adding the skipCrds to the crds or not.

**Comment by jgwest** [comment]
This will be fixed for `master` by https://github.com/argoproj/applicationset/pull/502
And 0.4.0 already includes the fix.

**Comment by EStork09** [comment]
Wow, you are good! Would you like me to close this as resolved or wait for the PR to be merged?
