### ISSUE TITLE
[scmProvider] - Github repos with no branches cause scmProvider to fail

### ISSUE THREAD

**Issue by gzur** [argoproj/applicationset#503]
## Overview
There are basically two problems here:
1. A single misconfigured repo inside a Github organisation crashes the reconcile loop for an `scmProvider`
2. Filtering out misbehaving repos does not work.

## What did I expect to happen?
1. I expect the controller to disregard repositories that do not match the filter.
2. I expect the `applicationset-controller` to survive misconfiguration of repositories that are not being targeted.

### Filter does not seem to work
I have an AppSet definition which uses the `scmProvider` with the following filter:
```
[...]
        - scmProvider:  
            cloneProtocol: ssh
            filters:
              - repositoryMatch: ^dh-
```
Despite this filter, the `applicationset-controller`  is throwing out errors while trying to enumerate the branches of a repo called `monorepo` (which doesn't fit the filters).

### Reconciler error
The repo in question not having any no branches. This makes the `applicationset-controller` fail to reconcile the AppSet definition with the following error:
```
time="2022-02-15T12:05:32Z" level=error msg="error generating params" error="error listing repos: error listing branches for github-org/monorepo: GET https://api.github.com/repos/github-org/monorepo/branches/main: 404 Branch not found []" generator="&{0xc00050f9a0 <nil>}"
time="2022-02-15T12:05:32Z" level=error msg="error generating params" error="child generator returned an error on parameter generation: error listing repos: error listing branches for github-org/monorepo: GET https://api.github.com/repos/github-org/monorepo/branches/main: 404 Branch not found []" generator="&{map[ClusterDecisionResource:0xc0001856d0 Clusters:0xc000185680 Git:0xc0007bdf50 List:0x3e24b38 Matrix:0xc000524bb0 Merge:0xc000524bb8 PullRequest:0xc0006fd830 SCMProvider:0xc00030e680]}"
time="2022-02-15T12:05:32Z" level=error msg="error generating application from params" error="child generator returned an error on parameter generation: error listing repos: error listing branches for github-org/monorepo: GET https://api.github.com/repos/github-org/monorepo/branches/main: 404 Branch not found []" generator="{<nil> <nil> <nil> <nil> <nil> <nil> <nil> 0xc000532780}"
2022-02-15T12:05:32.856Z	ERROR	controller-runtime.manager.controller.applicationset	Reconciler error	{"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "services-apps", "namespace": "argocd", "error": "child generator returned an error on parameter generation: error listing repos: error listing branches for github-org/monorepo: GET https://api.github.com/repos/github-org/monorepo/branches/main: 404 Branch not found []"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
```

**Comment by gzur** [comment]
I have a repro using my own org: `gzur-org`. It's just two repos - one [empty](https://github.com/gzur-org/empty-repo) and [one not](https://github.com/gzur-org/nonempty-repo).


I think a solution to this would have to [perform repository filtering](https://github.com/argoproj/applicationset/blob/0edd1527bb73fa3c8e8578a1a6124e71412f5403/pkg/services/scm_provider/utils.go#L98) before [attempting to fetch all branches](https://github.com/argoproj/applicationset/blob/0edd1527bb73fa3c8e8578a1a6124e71412f5403/pkg/services/scm_provider/utils.go#L85).

**Comment by crenshaw-dev** [comment]
I think https://github.com/argoproj/applicationset/pull/472 might resolve this.

If you have time to test against your repro org, that would be appreciated! If not I'll try to get to it asap.

**Comment by crenshaw-dev** [comment]
Actually I was super curious, so I tested. 😆 #472 does solve the problem if you add a filter. But it still fails if you don't have a filter.

I'll write up a test and see if it's reasonably easy to handle no-branch repos.
