### ISSUE TITLE
Way to prevent accidental deletion of all applications

### ISSUE THREAD

**Issue by Laakso** [argoproj/applicationset#560]
In our organization we were discussing what could happen if the ApplicationSet manifest that defines tens of different applications would be accidentally wiped from the cluster. So I started look into it and opened slack [thread](https://cloud-native.slack.com/archives/C01U45M2SVB/p1648126691841449) in the #argo-cd-appset channel. It revealed that there is not yet any mechanism to prevent resources from being wiped after accidental deletion of the ApplicationSet manifest. Controlled way of deleting ApplicationSet is naturally supported as described in the [documentation](https://argocd-applicationset.readthedocs.io/en/stable/Application-Deletion/).

So in case of accidental deletion - all the Applications will be wiped from the cluster.

So having a mechanism to retain resources in case of such incident would be awesome.

**Comment by romuduck** [comment]
hello,
what about this option at controller level: ```--policy create-update```?

**Comment by Laakso** [comment]
@romuduck oh wow. This is what we will end up using:
```
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
   ```
